import{S as v,a as f,i as m}from"./assets/vendor-89feecc5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const h="41588863-34d6c5c01e7f0c7c667666520",p=document.querySelector("#search-input"),b=document.querySelector("#image-container"),i=document.querySelector(".loader"),C=document.querySelector("#search-form"),w=new v("#image-container a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".load-more-btn"),t={currentPage:1,totalHits:0,query:"",currentQuery:""};let u;C.addEventListener("submit",$);y.addEventListener("click",S);async function $(s){s.preventDefault(),t.currentPage=1,d();const r=p.value.trim();if(!r){c();return}i.style.display="block",r!==t.currentQuery&&(t.currentQuery=r);const n=`https://pixabay.com/api/?key=${h}&q=${t.currentQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${t.currentPage}&per_page=40`;try{const e=(await f.get(n)).data;i.style.display="none",Array.isArray(e.hits)&&e.hits.length>0?(t.totalHits=e.totalHits,d(),t.currentPage<Math.ceil(t.totalHits/40)&&q(),L(e.hits),w.refresh()):(d(),c(),m.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"topRight"}),t.totalHits<40&&c())}catch(a){i.style.display="none",console.error("Error!",a)}t.query=t.currentQuery,p.value=""}function L(s){s.map(r=>{const n=`
      <div class="image-card">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}">
          <div class="image-info">
            <p><strong>Likes:</strong> ${r.likes}</p>
            <p><strong>Views:</strong> ${r.views}</p>
            <p><strong>Comments:</strong> ${r.comments}</p>
            <p><strong>Downloads:</strong> ${r.downloads}</p>
          </div>
        </a>
      </div>
    `;b.insertAdjacentHTML("beforeend",n)})}function d(){t.query!==t.currentQuery&&(b.innerHTML="")}function q(){y.style.display="block"}function c(){y.style.display="none"}async function S(){t.query=t.currentQuery,i.style.display="block",t.currentPage++;const s=`https://pixabay.com/api/?key=${h}&q=${t.currentQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${t.currentPage}&per_page=40`;try{const n=(await f.get(s)).data;if(i.style.display="none",Array.isArray(n.hits)&&n.hits.length>0)if(L(n.hits),w.refresh(),t.currentPage<Math.ceil(t.totalHits/40)){q();const a=document.querySelector(".image-card");a&&(u=a.getBoundingClientRect().height,g(u*2))}else g(u*2),c(),m.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"orange",position:"topRight"})}catch(r){i.style.display="none",console.error("Error!",r)}}function g(s){document.querySelector(".image-card")&&window.scrollBy({top:s,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
