import{S as C,a as p,i as u}from"./assets/vendor-89feecc5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const y="41588863-34d6c5c01e7f0c7c667666520",c=document.querySelector("#search-input"),f=document.querySelector("#image-container"),i=document.querySelector(".loader"),w=document.querySelector("#search-form"),b=new C("#image-container a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".load-more-btn"),o={currentPage:1,totalHits:0,query:""};let d;w.addEventListener("submit",L);h.addEventListener("click",S);function L(a){if(a.preventDefault(),o.query=c.value.trim(),!o.query){m(),g();return}i.style.display="block";const r=`https://pixabay.com/api/?key=${y}&q=${o.query}&image_type=photo&orientation=horizontal&safesearch=true&page=${o.currentPage}&per_page=40`;p.get(r).then(e=>{const s=e.data;i.style.display="none",Array.isArray(s.hits)&&s.hits.length>0?(o.totalHits=s.totalHits,q(s.hits),b.refresh(),c.value="",setTimeout(()=>{v()},0),o.currentPage++):(m(),g(),o.totalHits===0?u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"topRight"}):(u.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"orange",position:"topRight"}),c.value="",o.currentPage=1))}).catch(e=>{i.style.display="none",console.error("Error!",e)})}function q(a){a.map(e=>{const s=`
      <div class="image-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <div class="image-info">
            <p><strong>Likes:</strong> ${e.likes}</p>
            <p><strong>Views:</strong> ${e.views}</p>
            <p><strong>Comments:</strong> ${e.comments}</p>
            <p><strong>Downloads:</strong> ${e.downloads}</p>
          </div>
        </a>
      </div>
    `;f.innerHTML+=s});const r=document.querySelector(".image-card");r&&(d=r.getBoundingClientRect().height)}function m(){f.innerHTML=""}function v(){h.style.display="block"}function g(){h.style.display="none"}function S(){if(o.query=c.value.trim(),o.currentPage<=Math.ceil(o.totalHits/40)){i.style.display="block";const a=`https://pixabay.com/api/?key=${y}&q=${o.query}&image_type=photo&orientation=horizontal&safesearch=true&page=${o.currentPage}&per_page=40`;p.get(a).then(r=>{const e=r.data;if(i.style.display="none",Array.isArray(e.hits)&&e.hits.length>0){q(e.hits),b.refresh(),o.currentPage++;const s=document.querySelector(".image-card");s&&(d=s.getBoundingClientRect().height,$(d*2)),setTimeout(()=>{v()},0)}}).catch(r=>{i.style.display="none",console.error("Error!",r)})}else g(),u.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"orange",position:"topRight"})}function $(a){document.querySelector(".image-card")&&window.scrollBy({top:a,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
