import{S as L,a as f,i as u}from"./assets/vendor-89feecc5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const h="41588863-34d6c5c01e7f0c7c667666520",l=document.querySelector("#search-input"),m=document.querySelector("#image-container"),i=document.querySelector(".loader"),q=document.querySelector("#search-form"),b=new L("#image-container a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".load-more-btn"),e={currentPage:1,totalHits:0,query:"",currentQuery:""};let g;q.addEventListener("submit",C);y.addEventListener("click",$);async function C(s){s.preventDefault();const o=l.value.trim();if(!o){d();return}i.style.display="block",o!==e.currentQuery&&(p(),e.currentQuery=o,e.currentPage=1);const r=`https://pixabay.com/api/?key=${h}&q=${e.currentQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${e.currentPage}&per_page=40`;try{const t=(await f.get(r)).data;i.style.display="none",Array.isArray(t.hits)&&t.hits.length>0?(e.totalHits=t.totalHits,p(),e.currentPage<=Math.ceil(e.totalHits/40)&&v(),w(t.hits),b.refresh(),l.value="",e.currentPage++):(d(),e.totalHits===0?u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"topRight"}):(u.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"orange",position:"topRight"}),l.value=""))}catch(a){i.style.display="none",console.error("Error!",a)}e.query=e.currentQuery}function w(s){s.map(r=>{const a=`
      <div class="image-card">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}">
          <div class="image-info">
            <p><strong>Likes:</strong> ${r.likes}</p>
            <p><strong>Views:</strong> ${r.views}</p>
            <p><strong>Comments:</strong> ${r.comments}</p>
            <p><strong>Downloads:</strong> ${r.downloads}</p>
          </div>
        </a>
      </div>
    `;m.insertAdjacentHTML("beforeend",a)});const o=document.querySelector(".image-card");o&&(g=o.getBoundingClientRect().height,k(g*2))}function p(){e.query!==e.currentQuery&&(m.innerHTML="")}function v(){y.style.display="block"}function d(){y.style.display="none"}async function $(){e.query=e.currentQuery,i.style.display="block";const s=`https://pixabay.com/api/?key=${h}&q=${e.currentQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${e.currentPage}&per_page=40`;try{const r=(await f.get(s)).data;i.style.display="none",Array.isArray(r.hits)&&r.hits.length>0&&(w(r.hits),b.refresh(),e.currentPage++,e.currentPage<=Math.ceil(e.totalHits/40)?v():(d(),u.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"orange",position:"topRight"})))}catch(o){i.style.display="none",console.error("Error!",o)}}function k(s){document.querySelector(".image-card")&&window.scrollBy({top:s,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
